CREATE TABLE customer (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  nama VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
);

CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE produk (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  nama_produk VARCHAR(100) NOT NULL,
  harga DECIMAL(10,3) NOT NULL,
  kategori_produk VARCHAR(20) NOT NULL,
  dosis_produk VARCHAR(255) NOT NULL,
  deskripsi_produk VARCHAR(300) NOT NULL,
  gambar VARCHAR(100) NOT NULL
);
